#include <stdio.h>
#include <uxhw.h>
#include <math.h>


/*
 *	Model of lift force generated by an airfoil, based on the Bernoulli equation
 *
 *	Inputs:
 *	The inputs and their ranges are:
 *	-	`CL` Lift coefficient: 1.2
 *	-	`A` Area of the airfoil: 30
 *	-	`v` Airspeed calculated from Pitot tube data: 60 to 120 (uniform distribution)
 *	-	`T` Temperature at the surface: 298 to 302 (gaussian distribution)
 *	-	`h` Altitud: 3000 to 9000 (uniform distribution)
 *	-	`RH` Relative Humidity: 0.4 to 0.6 (uniform distribution)
 *	-	`TR` Temperature lapse rate: 0.006 to 0.007 (uniform distribution)
 *
 */

// CONSTANTS 
#define P0 101325 // Standard pressure at sea level
#define Rd 287.05 // Gas constant for dry air

static void computeDensity(double * rho, double T, double h, double RH, double TR)
{
	double Th = T - TR * h;
	*rho = P0/(Rd * Th) * (1 - 0.378 * RH);
}

static void computeLift(double * L, double CL, double rho, double A, double v)
{
	*L = 0.5 * CL * rho * A * v * v;
}

static void loadInputs(double * CL, double * A, double * v, double * T, double * h, double * RH, double * TR)
{
	*CL = 1.2;
	*A = 30;
	*v	= UxHwDoubleUniformDist(60, 120);
	*T = UxHwDoubleGaussDist(300, 2);
	*h	= UxHwDoubleUniformDist(3000, 9000);
	*RH = UxHwDoubleUniformDist(0.4, 0.6);
	*TR = UxHwDoubleUniformDist(0.006, 0.007);
}

int
main(int argc, char *  argv[])
{
	double	CL, A, v, T, h, RH, TR, rho, L;

	loadInputs(&CL, &A, &v, &T, &h, &RH, &TR);

	printf("Lift coefficient = %lf\n", CL);
	printf("Airfoil effective area = %lf\n", A);
	printf("Airspeed = %lf\n", v);
	printf("Temperature = %lf\n", T);
	printf("Altitud = %lf\n", h);
	printf("Relative Humidity = %lf\n", RH);

	computeDensity(&rho, T, h, RH, TR);
	computeLift(&L, CL, rho, A, v);

	printf("Lift = %lf\n", L);

	return 0;
}

